services:
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    networks:
      - servarr
    ports:
      - "6767:6767"
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK=002
      - TZ=Europe/Amsterdam
      - WEBUI_PORTS=6767/tcp,6767/udp
    volumes:
      - ./config:/config
      - /data:/data

networks:
  servarr:
    external: true
